### PR TITLE
Add Indonesian Language And Fix Editor Page

### PR DESCRIPTION
**Pull request by azkadev**
Tested On Linux

Screenshot from 2023-07-28 15-22-50
Screenshot from 2023-07-28 15-22-55
Screenshot from 2023-07-28 15-23-06

### CODE REVIEW

**Comment by azkadev** [comment]
Tested on Android 11
photo_2023-07-28_15-36-32
photo_2023-07-28_15-36-31
photo_2023-07-28_15-36-30
photo_2023-07-28_15-36-28
photo_2023-07-28_15-36-27
photo_2023-07-28_15-36-22
photo_2023-07-28_15-36-20

**Review by lollipopkit — APPROVED** [review]

**Comment by lollipopkit** [comment]
Thanks for your contribution

**Comment by lollipopkit** [comment]
Could you please send me an email?

`lollipopkitqq.com` (insert `@` before `qq.com`)

I'll privately send you 10 iOS App redemption codes as a thank for your contribution.

It will expire in 30 days.

**Comment by azkadev** [comment]
> I'll privately send you 10 iOS App redemption codes as a thank for your contribution.

Thank you very much for your attention, but sorry it's not necessary because I don't have an iOS device, sorry my English is bad

**Comment by lollipopkit** [comment]
This is the only way i can thank you.
You can gift it to someone else.
:)

**Pull request closed without merging**
