### PR TITLE
fix: chinese font display

### PR DESCRIPTION
**Pull request by No06**
fix https://github.com/lollipopkit/flutter_server_box/issues/397

before
57fd555207eadbca81653c6b2c42e8f9

after
16cff8dd0d4e71f4defdd76807496f42

### CODE REVIEW

**Comment by lollipopkit** [comment]
- Check system lang at first, if Chinese (eg. `LC_ALL | LANG` on Linux), use it.
- macOS doesn't have this issue

**Comment by lin-calvin** [comment]
Only enable on WIndows since Linux,Macos,Andorid dont have this issue? or provide a setting item to let user to decide enable it or not

**Comment by No06** [comment]
更多的是修复，而不是修改，理应不会产生新的问题。

这个操作也只是为 `textTheme` 的 `fontFamilyFallback` 添加备用字体，当无法找到或渲染主字体时，它会按顺序尝试使用 `fontFamilyFallback` 中列出的字体。

所以不需要另外判断是否是中文用户，或者其他平台的用户。

参阅源代码 [LastMonopoly/chinese_font_library/chinese_font_library.dart#L74](https://github.com/LastMonopoly/chinese_font_library/blob/master/lib/src/system_chinese_font.dart#L74)

**Comment by lollipopkit** [comment]
Sorry, this pr will be closed

**Pull request closed without merging**
